### ISSUE TITLE
Missing atmosphere history and master files in forecast with a long list of "OUTPUT_FH" in model configure

### ISSUE THREAD

**Issue by XiaqiongZhou-NOAA** [ufs-community/ufs-weather-model#2685]
## Description

When OUTPUT_FH in model_configure is a long list (6 12 18...2976), the forecast is finished fine, and ocean and ice output files are also OK except that the model stopped writing out atmospheric history and master files after f2616.

### To Reproduce:

It was seen in both WCOSS2 and Hera
The package to reproduce the issue saves on Hera:
/scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/sfscase
The log file ~/out
The rundirectory: ~RUNDIR/C96_test
The model can finish 2976-hour forecasts, but the no output after GFSPRS.GrbF2616

To reproduce:
1)copy /scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/sfscase 
1)sbatch run.sh

**output logs**
/scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/sfscase/out

**Comment by NickSzapiro-NOAA** [comment]
Thanks @XiaqiongZhou-NOAA! Looks like restart_interval in model_configure is just being read in wrong from ESMF_ConfigGetLen @danrosen25, with 218 instead of the 248 items.

Code summary:
```
num_restart_interval = ESMF_ConfigGetLen(config=CF, label ='restart_interval:',rc=rc)
if (mype == 0) print *,'af ufs config,num_restart_interval=',num_restart_interval
call ESMF_ConfigGetAttribute(CF,valueList=restart_interval,label='restart_interval:', &
                                 count=num_restart_interval, rc=rc)
if (mype == 0) print *,'af ufs config,restart_interval=',restart_interval
```

In out:
```
  0:  af ufs config,num_restart_interval=         218
  0:  af ufs config,restart_interval=   12.00000       24.00000       36.00000
  0:    48.00000       60.00000       72.00000       84.00000       96.00000
  0:    108.0000       120.0000       132.0000       144.0000       156.0000
  0:    168.0000       180.0000       192.0000       204.0000       216.0000
  0:    228.0000       240.0000       252.0000       264.0000       276.0000
  0:    288.0000       300.0000       312.0000       324.0000       336.0000
  0:    348.0000       360.0000       372.0000       384.0000       396.0000
  0:    408.0000       420.0000       432.0000       444.0000       456.0000
  0:    468.0000       480.0000       492.0000       504.0000       516.0000
  0:    528.0000       540.0000       552.0000       564.0000       576.0000
  0:    588.0000       600.0000       612.0000       624.0000       636.0000
  0:    648.0000       660.0000       672.0000       684.0000       696.0000
  0:    708.0000       720.0000       732.0000       744.0000       756.0000
  0:    768.0000       780.0000       792.0000       804.0000       816.0000
  0:    828.0000       840.0000       852.0000       864.0000       876.0000
  0:    888.0000       900.0000       912.0000       924.0000       936.0000
  0:    948.0000       960.0000       972.0000       984.0000       996.0000
  0:    1008.000       1020.000       1032.000       1044.000       1056.000
  0:    1068.000       1080.000       1092.000       1104.000       1116.000
  0:    1128.000       1140.000       1152.000       1164.000       1176.000
  0:    1188.000       1200.000       1212.000       1224.000       1236.000
  0:    1248.000       1260.000       1272.000       1284.000       1296.000
  0:    1308.000       1320.000       1332.000       1344.000       1356.000
  0:    1368.000       1380.000       1392.000       1404.000       1416.000
  0:    1428.000       1440.000       1452.000       1464.000       1476.000
  0:    1488.000       1500.000       1512.000       1524.000       1536.000
  0:    1548.000       1560.000       1572.000       1584.000       1596.000
  0:    1608.000       1620.000       1632.000       1644.000       1656.000
  0:    1668.000       1680.000       1692.000       1704.000       1716.000
  0:    1728.000       1740.000       1752.000       1764.000       1776.000
  0:    1788.000       1800.000       1812.000       1824.000       1836.000
  0:    1848.000       1860.000       1872.000       1884.000       1896.000
  0:    1908.000       1920.000       1932.000       1944.000       1956.000
  0:    1968.000       1980.000       1992.000       2004.000       2016.000
  0:    2028.000       2040.000       2052.000       2064.000       2076.000
  0:    2088.000       2100.000       2112.000       2124.000       2136.000
  0:    2148.000       2160.000       2172.000       2184.000       2196.000
  0:    2208.000       2220.000       2232.000       2244.000       2256.000
  0:    2268.000       2280.000       2292.000       2304.000       2316.000
  0:    2328.000       2340.000       2352.000       2364.000       2376.000
  0:    2388.000       2400.000       2412.000       2424.000       2436.000
  0:    2448.000       2460.000       2472.000       2484.000       2496.000
  0:    2508.000       2520.000       2532.000       2544.000       2556.000
  0:    2568.000       2580.000       2592.000       2604.000       2616.000
```

**Comment by danrosen25** [comment]
Hi @NickSzapiro-NOAA 
Can you post the model_configure file or email it to me? I'll make a reproducer and test it. And also let me know the version of ESMF being used.

Thanks
- Dan

**Comment by NickSzapiro-NOAA** [comment]
@danrosen25 I think ESMF 8.6.0

[model_configure_kate.txt](https://github.com/user-attachments/files/19651310/model_configure_kate.txt)

**Comment by DusanJovic-NOAA** [comment]
> Thanks [@XiaqiongZhou-NOAA](https://github.com/XiaqiongZhou-NOAA)! Looks like restart_interval in model_configure is just being read in wrong from ESMF_ConfigGetLen [@danrosen25](https://github.com/danrosen25), with 218 instead of the 248 items.
> 
> Code summary:
> 
> ```
> num_restart_interval = ESMF_ConfigGetLen(config=CF, label ='restart_interval:',rc=rc)
> if (mype == 0) print *,'af ufs config,num_restart_interval=',num_restart_interval
> call ESMF_ConfigGetAttribute(CF,valueList=restart_interval,label='restart_interval:', &
>                                  count=num_restart_interval, rc=rc)
> if (mype == 0) print *,'af ufs config,restart_interval=',restart_interval
> ```
> 
> In out:
> 
> ```
>   0:  af ufs config,num_restart_interval=         218
>   0:  af ufs config,restart_interval=   12.00000       24.00000       36.00000
>   0:    48.00000       60.00000       72.00000       84.00000       96.00000
>   0:    108.0000       120.0000       132.0000       144.0000       156.0000
>   0:    168.0000       180.0000       192.0000       204.0000       216.0000
>   0:    228.0000       240.0000       252.0000       264.0000       276.0000
>   0:    288.0000       300.0000       312.0000       324.0000       336.0000
>   0:    348.0000       360.0000       372.0000       384.0000       396.0000
>   0:    408.0000       420.0000       432.0000       444.0000       456.0000
>   0:    468.0000       480.0000       492.0000       504.0000       516.0000
>   0:    528.0000       540.0000       552.0000       564.0000       576.0000
>   0:    588.0000       600.0000       612.0000       624.0000       636.0000
>   0:    648.0000       660.0000       672.0000       684.0000       696.0000
>   0:    708.0000       720.0000       732.0000       744.0000       756.0000
>   0:    768.0000       780.0000       792.0000       804.0000       816.0000
>   0:    828.0000       840.0000       852.0000       864.0000       876.0000
>   0:    888.0000       900.0000       912.0000       924.0000       936.0000
>   0:    948.0000       960.0000       972.0000       984.0000       996.0000
>   0:    1008.000       1020.000       1032.000       1044.000       1056.000
>   0:    1068.000       1080.000       1092.000       1104.000       1116.000
>   0:    1128.000       1140.000       1152.000       1164.000       1176.000
>   0:    1188.000       1200.000       1212.000       1224.000       1236.000
>   0:    1248.000       1260.000       1272.000       1284.000       1296.000
>   0:    1308.000       1320.000       1332.000       1344.000       1356.000
>   0:    1368.000       1380.000       1392.000       1404.000       1416.000
>   0:    1428.000       1440.000       1452.000       1464.000       1476.000
>   0:    1488.000       1500.000       1512.000       1524.000       1536.000
>   0:    1548.000       1560.000       1572.000       1584.000       1596.000
>   0:    1608.000       1620.000       1632.000       1644.000       1656.000
>   0:    1668.000       1680.000       1692.000       1704.000       1716.000
>   0:    1728.000       1740.000       1752.000       1764.000       1776.000
>   0:    1788.000       1800.000       1812.000       1824.000       1836.000
>   0:    1848.000       1860.000       1872.000       1884.000       1896.000
>   0:    1908.000       1920.000       1932.000       1944.000       1956.000
>   0:    1968.000       1980.000       1992.000       2004.000       2016.000
>   0:    2028.000       2040.000       2052.000       2064.000       2076.000
>   0:    2088.000       2100.000       2112.000       2124.000       2136.000
>   0:    2148.000       2160.000       2172.000       2184.000       2196.000
>   0:    2208.000       2220.000       2232.000       2244.000       2256.000
>   0:    2268.000       2280.000       2292.000       2304.000       2316.000
>   0:    2328.000       2340.000       2352.000       2364.000       2376.000
>   0:    2388.000       2400.000       2412.000       2424.000       2436.000
>   0:    2448.000       2460.000       2472.000       2484.000       2496.000
>   0:    2508.000       2520.000       2532.000       2544.000       2556.000
>   0:    2568.000       2580.000       2592.000       2604.000       2616.000
> ```

Isn't the issue with `output_fh`, not with `restart_interval`?

**Comment by XiaqiongZhou-NOAA** [comment]
it seems that writing restart files also stop at f2616hr

**Comment by NickSzapiro-NOAA** [comment]
I've added the model_configure from /scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/sfscase/RUNDIR/C96_test/model_configure

Looks like both, @DusanJovic-NOAA. output_fh is from a idfferent call as well:
`call ESMF_InfoGetAlloc(info, key="output_fh", values=output_fh, rc=rc)`

**Comment by DusanJovic-NOAA** [comment]
This should be fixed once we update esmf from 8.6.0

**Comment by danrosen25** [comment]
@NickSzapiro-NOAA @XiaqiongZhou-NOAA 
We didn't fix the line limitation for ESMF Config until ESMF v8.6.1. Any subsequent release also includes this fix.
https://github.com/esmf-org/esmf/releases/tag/v8.6.1

In v8.6.0 each configuration line can be up to approximately 1024 characters.

**Comment by junwang-noaa** [comment]
@XiaqiongZhou-NOAA Please try the Spack-stack 1.9.1 branch on hera from:

https://github.com/ufs-community/ufs-weather-model/pull/2650/

**Comment by XiaqiongZhou-NOAA** [comment]
> [@XiaqiongZhou-NOAA](https://github.com/XiaqiongZhou-NOAA) Please try the Spack-stack 1.9.1 branch on hera from:
> 
> [#2650](https://github.com/ufs-community/ufs-weather-model/pull/2650)

SS191 was tested on Hera. The model output and restart files can write fine now after 2616 with a long list of OUTPUT_FH and restart_interval.
